from __future__ import annotations
from typing import Protocol
from torch.utils.data import DataLoader
from torch import nn
import torch

class ContinualMethod(Protocol):
    name: str
    def penalty(self) -> torch.Tensor: ...
    def before_task(self, model: nn.Module, train_loader: DataLoader, val_loader: DataLoader) -> None: ...
    def after_task(self,  model: nn.Module, train_loader: DataLoader, val_loader: DataLoader) -> None: ...
    # Hooks opcionales:
    def before_epoch(self, model: nn.Module, epoch: int) -> None: ...
    def after_epoch(self,  model: nn.Module, epoch: int) -> None: ...
    def before_batch(self, model: nn.Module, batch) -> None: ...
    def after_batch(self,  model: nn.Module, batch, loss: torch.Tensor) -> None: ...
    # Parámetro regulable opcional (para sugerencias neutrales en el trainer):
    def tunable(self) -> dict: ...
