defaults: &defaults
  model: &defaults_model
    name: pilotnet_snn
    img_w: 200
    img_h: 66
    to_gray: true

  data: &defaults_data
    encoder: rate
    T: 10
    gain: 0.5
    use_offline_spikes: true
    use_offline_balanced: false
    encode_runtime: false
    seed: 42
    num_workers: 8
    prefetch_factor: 2
    pin_memory: true
    persistent_workers: true
    aug_train: &aug_light
      prob_hflip: 0.5
      brightness: null
      gamma: null
      noise_std: 0.0
    balance_online: false
    balance_bins: 21
    balance_smooth_eps: 0.001

  optim: &defaults_optim
    amp: true
    lr: 0.001
    epochs: 2
    es_patience: null
    es_min_delta: null
    batch_size: 64

  continual: &defaults_continual
    method: naive
    params: {}

  naming: &defaults_naming
    tag: ""

  # parámetros por defecto del preprocesado/balanceo
  prep: &defaults_prep
    runs: ["circuito1", "circuito2"]   # puedes quitarlo para autodetección
    use_left_right: true
    steer_shift: 0.2
    bins: 21
    train: 0.70
    val: 0.15
    seed: 42
    target_per_bin: "auto"             # activa balanceo offline
    cap_per_bin: 12000

fast:
  <<: *defaults
  data:
    <<: *defaults_data
    T: 10
  optim:
    <<: *defaults_optim
    epochs: 2
    batch_size: 64
  continual:
    <<: *defaults_continual
    method: naive
    params: {}
  # 👇 NUEVO: hereda prep por defecto; puedes sobrescribir si quieres
  prep:
    <<: *defaults_prep
    # p.ej. bins: 19

std:
  <<: *defaults
  data:
    <<: *defaults_data
    T: 16
  optim:
    <<: *defaults_optim
    lr: 0.0005
    epochs: 8
    batch_size: 56
    es_patience: 3
    es_min_delta: 1.0e-4
  continual:
    <<: *defaults_continual
    method: ewc
    params:
      lam: 1.0e9
      fisher_batches: 1000
  prep:
    <<: *defaults_prep

accurate:
  <<: *defaults
  data:
    <<: *defaults_data
    T: 30
  optim:
    <<: *defaults_optim
    lr: 7.5e-4
    epochs: 20
    batch_size: 16
  continual:
    <<: *defaults_continual
    method: rehearsal+ewc
    params:
      buffer_size: 5000
      replay_ratio: 0.2
      lam: 1.0e9
      fisher_batches: 1500
  prep:
    <<: *defaults_prep
