# =====================
# PRESETS TFM — SNN/CL
# =====================

# ---- Bloque base (anclas) ----
defaults: &defaults
  model: &defaults_model
    name: pilotnet_snn
    img_w: 200
    img_h: 66
    to_gray: true

  data: &defaults_data
    # Codificación
    encoder: rate              # rate | latency | raw | image
    T: 10
    gain: 0.5
    use_offline_spikes: true   # H5 offline
    encode_runtime: false      # solo si use_offline_spikes=false

    # Reproducibilidad / rendimiento
    seed: 42
    num_workers: 8
    prefetch_factor: 2
    pin_memory: true
    persistent_workers: true

    # Aumentos (ligeros por defecto)
    aug_train: &aug_light
      prob_hflip: 0.5
      brightness: [0.9, 1.1]
      contrast:   [0.9, 1.1]
      saturation: [0.9, 1.1]
      hue:        [-0.03, 0.03]
      gamma: null
      noise_std: 0.0

    # Balanceo online (desactivado por defecto)
    balance_online: false
    balance_bins: 50
    balance_smooth_eps: 0.001

  # División/prepare (offline)
  prep: &defaults_prep
    runs: ["circuito1", "circuito2"]  # o [] si autodetectas
    merge_subruns: true
    use_left_right: true
    steer_shift: 0.2
    bins: 50
    train: 0.70
    val: 0.15
    seed: 42
    # Balanceo offline de imágenes (si tu pipeline lo usa)
    balance_offline:
      mode: images            # images | none
      target_per_bin: auto
      cap_per_bin: 12000
      aug:
        prob_hflip: 0.0       # desactivar en offline; fotométricos solo
        brightness: [0.8, 1.2]
        contrast:   [0.8, 1.2]
        saturation: [0.8, 1.2]
        hue:        [-0.1, 0.1]
        gamma: null
        noise_std: 0.0
    tasks_file_name: tasks.json
    tasks_balanced_file_name: tasks_balanced.json
    use_balanced_tasks: true
    encode_h5: false          # se puede activar en un preset

  optim: &defaults_optim
    amp: true
    lr: 0.001
    epochs: 2
    es_patience: null
    es_min_delta: null
    batch_size: 64

  # EWC por defecto
  continual: &defaults_continual
    method: ewc
    params:
      lam: 1.0e9
      fisher_batches: 1000

  # Control de logs por preset
  logging: &defaults_logging
    telemetry:
      codecarbon: true
      offline: true
      country_iso_code: "ESP"
      measure_power_secs: 15
      log_level: "error"
    ewc:
      fisher_verbose: false
      inner_verbose:  false
      inner_every:    8192
    rehearsal:
      buffer_verbose: false
      replay_verbose: false
      replay_show_shapes: false
    as-snn:
      activity_verbose: false
      activity_every: 8192
    sa-snn:
      trace_verbose: false
      trace_every: 8192
    sca-snn:
      verbose: false
      log_every: 8192

  naming: &defaults_naming
    tag: ""

# ---- Presets ----

fast:
  <<: *defaults
  data:
    <<: *defaults_data
    T: 10
  optim:
    <<: *defaults_optim
    epochs: 2
    batch_size: 128
  continual:
    method: sa-snn
    params:
      # attach_to: "f6"
      k: 16
      tau: 10.0
      th_min: 1.0
      th_max: 2.0
      p: 2000000
      vt_scale: 1.0
      flatten_spatial: false
      assume_binary_spikes: false
      reset_counters_each_task: false
  prep:
    <<: *defaults_prep
  logging:
    <<: *defaults_logging
  naming:
    <<: *defaults_naming

std:
  <<: *defaults
  data:
    <<: *defaults_data
    T: 16
  optim:
    <<: *defaults_optim
    lr: 5.0e-4
    epochs: 8
    batch_size: 96
    es_patience: 3
    es_min_delta: 5.0e-4
  continual:
    method: sa-snn
    params:
      attach_to: "f6"     # 1ª densa de PilotNetSNN (N=100)
      k: 12               # ~12%
      tau: 20             # ≈1.25×T
      th_min: 1.0
      th_max: 2.0
      vt_scale: 1.25
      p: 3000000
      flatten_spatial: false
      assume_binary_spikes: false
      reset_counters_each_task: false
  prep:
    <<: *defaults_prep
  logging:
    <<: *defaults_logging
  naming:
    <<: *defaults_naming

accurate:
  <<: *defaults
  data:
    <<: *defaults_data
    T: 30
  optim:
    <<: *defaults_optim
    lr: 7.5e-4
    epochs: 20
    batch_size: 32
    es_patience: null
    es_min_delta: null
  continual:
    method: sa-snn
    params:
      attach_to: "f6"
      k: 8                # ~8% (más esparso → más estabilidad)
      tau: 30             # ≈T
      th_min: 1.0
      th_max: 2.0
      vt_scale: 1.5
      p: 5000000
      flatten_spatial: false
      assume_binary_spikes: false
      reset_counters_each_task: false
  prep:
    <<: *defaults_prep
  logging:
    <<: *defaults_logging
  naming:
    <<: *defaults_naming
